"""adding patient table

Revision ID: 82123b1deffb
Revises: 1a31ce608336
Create Date: 2025-02-16 12:38:30.397522

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '82123b1deffb'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_table',
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('about', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=False),
    sa.Column('EmailStr', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('activity_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('caregiver_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['caregiver_id'], ['caregiver.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('patient')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['caregiver.id'], name='patient_owner_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='patient_pkey')
    )
    op.drop_table('patient_table')
    # ### end Alembic commands ###